### ISSUE TITLE
好兄弟，新版本无法使用

### ISSUE THREAD

**Issue by liuhui677** [igzhang/shadowReader#10]
书打不开，添加书籍也没有反应了

**Comment by igzhang** [comment]
> 书打不开，添加书籍也没有反应了

可以说下vscode和插件的版本号吗？我试试

**Comment by cMing1997** [comment]
好雄蝶， 这个版本下，直接提示 not found
```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
```
![image](https://user-images.githubusercontent.com/40878104/129648299-244c9a11-a0b7-4082-b28d-215241cbf7ec.png)

**Comment by liuhui677** [comment]
> > 书打不开，添加书籍也没有反应了
> 
> 可以说下vscode和插件的版本号吗？我试试

版本: 1.59.0 (user setup)
提交: 379476f0e13988d90fab105c5c19e7abc8b1dea8
日期: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by liuhui677** [comment]
> > 书打不开，添加书籍也没有反应了
> 
> 可以说下vscode和插件的版本号吗？我试试

> 会不会是和其他插件冲突了

**Comment by liuhui677** [comment]
> > 书打不开，添加书籍也没有反应了
> 
> 可以说下vscode和插件的版本号吗？我试试

本地可以用，只有网络书籍用不了

**Comment by igzhang** [comment]
> > > 书打不开，添加书籍也没有反应了
> > 
> > 
> > 可以说下vscode和插件的版本号吗？我试试
> 
> 本地可以用，只有网络书籍用不了

可以提供下网络书籍哪个看不了吗？我本地没试出来

**Comment by igzhang** [comment]
> 好雄蝶， 这个版本下，直接提示 not found
> 
> ```
> Version: 1.59.0 (user setup)
> Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
> Date: 2021-08-04T23:13:12.822Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.19042
> ```
> 
> ![image](https://user-images.githubusercontent.com/40878104/129648299-244c9a11-a0b7-4082-b28d-215241cbf7ec.png)

看下插件，是被禁用了吗？

**Comment by liuhui677** [comment]
> > > > 书打不开，添加书籍也没有反应了
> > > 
> > > 
> > > 可以说下vscode和插件的版本号吗？我试试
> > 
> > 
> > 本地可以用，只有网络书籍用不了
> 
> 可以提供下网络书籍哪个看不了吗？我本地没试出来

我搜的三体，找不到。应该不是插件问题，应该是我vscode和插件冲突了，虽然现在只能能看本地也很好了

**Comment by igzhang** [comment]
> > > > > 书打不开，添加书籍也没有反应了
> > > > 
> > > > 
> > > > 可以说下vscode和插件的版本号吗？我试试
> > > 
> > > 
> > > 本地可以用，只有网络书籍用不了
> > 
> > 
> > 可以提供下网络书籍哪个看不了吗？我本地没试出来
> 
> 我搜的三体，找不到。应该不是插件问题，应该是我vscode和插件冲突了，虽然现在只能能看本地也很好了

发布了新版本，三体可以看了
PS:这个bug是章节选择那边的问题，我索性改成了选择框(doge)

**Comment by HueyZhang** [comment]
经常网络超时，不知道是我这里网络原因还是什么

**Comment by GOWxx** [comment]
vscode版本 (win10 运行于管理员模式 已禁用其他vscode插件)

版本: 1.60.1 (user setup)
提交: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
日期: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

插件版本
rainbroadcast.shadow-reader @0.5.3

添加/删除 本地书籍可以
网络书籍也可以搜索并添加
ctrl+shift+p 用命令 运行开始阅读 可以选择添加的书籍 不报错
但是状态栏没变化

文件是 .txt 格式, utf-8编码, 文件放在了.vscode\extensions\rainbroadcast.shadow-reader-0.5.3下新建了一个book文件夹里

**Comment by igzhang** [comment]
暂时先关了，有问题可以提单独的issue哦
