### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by wang-zh** [igzhang/shadowReader#11]
![image](https://user-images.githubusercontent.com/39694902/130893896-0dbc0b5f-2b4b-422b-bc38-da25b197eaea.png)
添加书籍这些都正常，但是在开始阅读的时候出现了上面的错误

**Comment by igzhang** [comment]
> ![image](https://user-images.githubusercontent.com/39694902/130893896-0dbc0b5f-2b4b-422b-bc38-da25b197eaea.png)
> 添加书籍这些都正常，但是在开始阅读的时候出现了上面的错误

是没读到内容，可以把txt或者在线书名发出来吗？

**Comment by wang-zh** [comment]
海贼之天空龙，就是点了开始阅读就没反应了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "igzhang/shadowReader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 晚上10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [igzhang/shadowReader] Cannot read property 'replace' of null (#11)





  

 添加书籍这些都正常，但是在开始阅读的时候出现了上面的错误
  
是没读到内容，可以把txt或者在线书名发出来吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by igzhang** [comment]
> 海贼之天空龙，就是点了开始阅读就没反应了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "igzhang/shadowReader" ***@***.***&gt;; 发送时间:&nbsp;2021年8月26日(星期四) 晚上10:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [igzhang/shadowReader] Cannot read property 'replace' of null (#11) 添加书籍这些都正常，但是在开始阅读的时候出现了上面的错误 是没读到内容，可以把txt或者在线书名发出来吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是章节查找的问题，已更新版本，删除原书籍重新添加就行啦
