### ISSUE TITLE
能否自定义换行分隔符

### ISSUE THREAD

**Issue by Wu-Haitao** [igzhang/shadowReader#12]
插件很棒，提个小建议：
我感觉这个分隔的空格有点多，本身空间不大，能紧密一些会更好。👇
![image](https://user-images.githubusercontent.com/59434361/134295717-ab1f7524-6051-4b81-b6f7-f1558fb2ecd5.png)
我看 Thief-Book-VSCode 它是能自定义，您看能否也添加这个功能呢？

**Comment by igzhang** [comment]
> 插件很棒，提个小建议：
> 我感觉这个分隔的空格有点多，本身空间不大，能紧密一些会更好。👇
> ![image](https://user-images.githubusercontent.com/59434361/134295717-ab1f7524-6051-4b81-b6f7-f1558fb2ecd5.png)
> 我看 Thief-Book-VSCode 它是能自定义，您看能否也添加这个功能呢？

好的，安排

**Comment by igzhang** [comment]
> 插件很棒，提个小建议：
> 我感觉这个分隔的空格有点多，本身空间不大，能紧密一些会更好。👇
> ![image](https://user-images.githubusercontent.com/59434361/134295717-ab1f7524-6051-4b81-b6f7-f1558fb2ecd5.png)
> 我看 Thief-Book-VSCode 它是能自定义，您看能否也添加这个功能呢？

已更新版本，新版本可配置啦
