### ISSUE TITLE
“certificate has expired”问题

### ISSUE THREAD

**Issue by lq4139** [igzhang/shadowReader#14]
今天打开插件后提示“certificate has expired”，提示证书过期了，这个怎么处理呢

**Comment by igzhang** [comment]
> 今天打开插件后提示“certificate has expired”，提示证书过期了，这个怎么处理呢

笔趣阁更换了新的域名引起的。
已经更新了插件版本，更新下就好啦

**Comment by lq4139** [comment]
我卸载了重装，然后重启vscode 还是提示证书过期
