### ISSUE TITLE
vscode状态栏字太小，看的眼疼

### ISSUE THREAD

**Issue by rzorzo** [igzhang/shadowReader#16]
vscode状态栏字太小，看的眼疼眼花。能增加个设置项可以自己设置字体大小吗？

**Comment by igzhang** [comment]
> vscode状态栏字太小，看的眼疼眼花。能增加个设置项可以自己设置字体大小吗？

这个vscode没有提供相应的方法呢，最早就是考虑给外接显示屏的划水用，笔记本屏幕确实小了。有其他创意吗？

**Comment by rzorzo** [comment]
有方法直接改vscode 的css吗？比如添加一个css样式文件
.monaco-workbench .part.statusbar { font-size: ?px;}
