### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by isolatedstar** [igzhang/shadowReader#18]
添加书籍Request failed with status code 500啥问题哇

**Comment by igzhang** [comment]
> 添加书籍Request failed with status code 500啥问题哇

笔趣阁的搜索功能报错了，还有其他靠谱的网站吗？我也可以加进去

**Comment by ghrt321** [comment]
添加书籍不能用了，，，，大佬快来，日常工作不能没你

**Comment by ghrt321** [comment]
https://www.caimoge.net/

**Comment by igzhang** [comment]
> https://www.caimoge.net/

马上安排，预计每天可以上线

**Comment by lq4139** [comment]
改了么改了么？在线等

**Comment by igzhang** [comment]
> https://www.caimoge.net/

测试了几次，网站挂了，咋联系站长？
![image](https://user-images.githubusercontent.com/37896061/155444027-20cca285-d1d7-4968-ac7b-ee73f217f1b3.png)

**Comment by lq4139** [comment]
我刚测试可以打开啊

**Comment by lq4139** [comment]
作者有没有微信群啥的呀，沟通起来方便，在这里沟通太慢了

**Comment by igzhang** [comment]
> 作者有没有微信群啥的呀，沟通起来方便，在这里沟通太慢了

没有呢，要不你加我微信吧，676529483

**Comment by igzhang** [comment]
> https://www.caimoge.net/
已添加，更新版本即可

**Comment by igzhang** [comment]
版本0.7.3已解决，更新版本即可
