### ISSUE TITLE
换行符替换

### ISSUE THREAD

**Issue by lvyulv** [igzhang/shadowReader#19]
你好，请问可以不使用换行符替换吗？
就希望和原文本的换行保持一致。
插件很好用~

**Comment by igzhang** [comment]
不替换换行符怎么显示呢？底部状态栏只能显示一行啊

**Comment by lvyulv** [comment]
就原先的一行如果是30个字符，每行设定最多显示50个字符，那显示的时候就显示这一行的30个字符。
如果原先的一行是60个字符，那就第50个字符截取，然后剩下的10个字符显示为下一行。
不知是否可行

**Comment by lvyulv** [comment]
> 不替换换行符怎么显示呢？底部状态栏只能显示一行啊

就原先的一行如果是30个字符，每行设定最多显示50个字符，那显示的时候就显示这一行的30个字符。
如果原先的一行是60个字符，那就第50个字符截取，然后剩下的10个字符显示为下一行。
不知是否可行

**Comment by igzhang** [comment]
可行，我这两天更新下

**Comment by igzhang** [comment]
> 

问下，你是本地书籍需要换行还是采墨阁？

**Comment by igzhang** [comment]
> > 不替换换行符怎么显示呢？底部状态栏只能显示一行啊
> 
> 就原先的一行如果是30个字符，每行设定最多显示50个字符，那显示的时候就显示这一行的30个字符。 如果原先的一行是60个字符，那就第50个字符截取，然后剩下的10个字符显示为下一行。 不知是否可行

已更新版本

**Comment by sobe1443** [comment]
这个更新后，后退有问题。后退好像是重新排列了，而且 感觉更新后没有之前看的舒服，还是每一行显示固定的字数好
