### ISSUE TITLE
最近老是403

### ISSUE THREAD

**Issue by zyuerugou** [igzhang/shadowReader#21]
最近老是报403错误，两个网址都是
Request failed with status code 403

**Comment by igzhang** [comment]
> 最近老是报403错误，两个网址都是 Request failed with status code 403

采墨阁是加了层cf的问题，笔趣E也不行吗？我这边可以用呢

**Comment by zyuerugou** [comment]
ok，我切一下源，删掉小说再试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月22日 16:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [igzhang/shadowReader] 最近老是403 (Issue #21) |

最近老是报403错误，两个网址都是 Request failed with status code 403

采墨阁是加了层cf的问题，笔趣E也不行吗？我这边可以用呢

**Comment by zyuerugou** [comment]
今天又用了一天，换源之后没有问题了，多谢大佬

**Comment by lgCode** [comment]
我现在用也是两个源都报403
