### ISSUE TITLE
设置超过80字符后显示不正确

### ISSUE THREAD

**Issue by CtriXin** [igzhang/shadowReader#4]
感觉像是status bar 区域的限制 导致超过一定字符后 显示不完全 这个有办法解决吗

**Comment by CtriXin** [comment]
设置同样数量 自带显示器和外接显示器显示内容不一致 外接的能显示全 自带显示器会截取一部分

**Comment by CtriXin** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/16875298/118237776-33c6eb80-b4ca-11eb-877a-4f91742fa6c9.png">

**Comment by CtriXin** [comment]
![image](https://user-images.githubusercontent.com/16875298/118237834-46412500-b4ca-11eb-9b05-f2f784a123ed.png)

**Comment by igzhang** [comment]
> 感觉像是status bar 区域的限制 导致超过一定字符后 显示不完全 这个有办法解决吗

是的，status bar没有明确说长度的问题，所以做成了配置项。有好建议吗？
