### ISSUE TITLE
在线的书只能在当前章节搜索，有办法做成在线的书直接跳转章节吗？

### ISSUE THREAD

**Issue by ZhangzhiS** [igzhang/shadowReader#5]

**Comment by ZhangzhiS** [comment]
是否可以做成自定义书源呢？开放接入书源的方式，可以自己配置

**Comment by igzhang** [comment]
> 是否可以做成自定义书源呢？开放接入书源的方式，可以自己配置

1. 应该可以向后搜索吧，我找时间试试
2. 自定义书源需要写代码实现，是否可以接受呢？

**Comment by igzhang** [comment]
too long to close

**Comment by ZhangzhiS** [comment]
> > 是否可以做成自定义书源呢？开放接入书源的方式，可以自己配置
> 
> 1. 应该可以向后搜索吧，我找时间试试
> 2. 自定义书源需要写代码实现，是否可以接受呢？

可以接受的
