### ISSUE TITLE
定时老板键

### ISSUE THREAD

**Issue by MerlinBlade** [igzhang/shadowReader#7]
- 新增一个定时器，若 N 秒内没有按下 <kbd>Alt</kbd> + <kbd>.</kbd>或<kbd>Alt</kbd> + <kbd>,</kbd>则自动触发<kbd>Alt</kbd> + <kbd>/</kbd>，防止临时离开时忘记按下老板键。
- <kbd>Alt</kbd> + <kbd>/</kbd> 变成 toggle button, 即按一下隐藏，再按一下显示。

**Comment by igzhang** [comment]
> * 新增一个定时器，若 N 秒内没有按下 Alt + .或Alt + ,则自动触发Alt + /，防止临时离开时忘记按下老板键。
> * Alt + / 变成 toggle button, 即按一下隐藏，再按一下显示。

这个不错，安排上

**Comment by igzhang** [comment]
> * 新增一个定时器，若 N 秒内没有按下 Alt + .或Alt + ,则自动触发Alt + /，防止临时离开时忘记按下老板键。
> * Alt + / 变成 toggle button, 即按一下隐藏，再按一下显示。

已实现，更新版本可得
